"""new beginning

Revision ID: eda36d28fc07
Revises: 
Create Date: 2021-10-26 01:04:30.086480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eda36d28fc07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('record_link', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_record_link'), 'record', ['record_link'], unique=True)
    op.create_index(op.f('ix_record_title'), 'record', ['title'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlist_link', sa.String(length=512), nullable=True),
    sa.Column('playlist_name', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlist_playlist_link'), 'playlist', ['playlist_link'], unique=True)
    op.create_index(op.f('ix_playlist_playlist_name'), 'playlist', ['playlist_name'], unique=False)
    op.create_table('RecordList',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlistId', sa.Integer(), nullable=True),
    sa.Column('recordId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['playlistId'], ['playlist.id'], ),
    sa.ForeignKeyConstraint(['recordId'], ['record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RecordList')
    op.drop_index(op.f('ix_playlist_playlist_name'), table_name='playlist')
    op.drop_index(op.f('ix_playlist_playlist_link'), table_name='playlist')
    op.drop_table('playlist')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_record_title'), table_name='record')
    op.drop_index(op.f('ix_record_record_link'), table_name='record')
    op.drop_table('record')
    # ### end Alembic commands ###
